// src/components/Navbar.vue
<template>
    <nav class="navbar">
      <h1>WIC</h1>
      <ul>
        <li><router-link to="/">Home</router-link></li>
        <li><router-link to="/dashboard">Dashboard</router-link></li>
        <li><router-link to="/login">Login</router-link></li>
        <li><router-link to="/register">Register</router-link></li>
      </ul>
    </nav>
  </template>
  
  <style scoped>
  .navbar {
    display: flex;
    justify-content: space-between;
    align-items: center;
    background-color: #111;
    color: #fff;
    padding: 1rem 2rem;
    font-family: 'Georgia', serif;
  }
  
  .navbar h1 {
    font-size: 1.5rem;
  }
  
  .navbar ul {
    list-style: none;
    display: flex;
    gap: 1rem;
  }
  
  .navbar a {
    color: #fff;
    text-decoration: none;
  }
  
  .navbar a:hover {
    text-decoration: underline;
  }
  </style>

// bijAndrea/src/components/NavBar.tsx
import { NavLink } from "react-router-dom";
export default function NavBar() {
  return (
    <nav className="bg-pink-100 p-4 flex justify-between items-center">
      <div className="text-2xl font-fancy">Andreas High Tea</div>
      <div className="space-x-4">
        <NavLink to="/" className="hover:underline">Home</NavLink>
        <NavLink to="/services" className="hover:underline">Eat Me</NavLink>
        <NavLink to="/teas" className="hover:underline">Drink Me</NavLink>
        <NavLink to="/contact" className="hover:underline">Contact</NavLink>
        <NavLink to="/booking" className="ml-2 px-3 py-1 bg-blue-200 rounded hover:bg-blue-300">
          Boek Nu
        </NavLink>
      </div>
    </nav>
)}
